language: node_js
node_js:
  - '12.6'
before_deploy:
  - npm prune --production
deploy:
  provider: lambda
  function_name: aws-events-should-make-sense
  module_name: aws-events-should-make-sense
  handler_name: makeSense
  role: arn:aws:iam::608300940987:role/lambda-aws-events-should-make-sense
  runtime: nodejs12.x
  timeout: 5
  memory_size: 128
  region: eu-west-1
  access_key_id:
    secure: Ux7J4Fp44gKAm29EzfB3Tx3LEg+M1AM/FY82kqUMA2ZhXPRiS5W2gWgf0sPTt55YvuEyjFNGF+N9cVTtpnGV+kPqZxqi4z8eX1+9e6yV3PCIHs6BHOMlHq8AqmKYXj893JT7RJS9bQcMeQ+ujeG2s85eetF/gVEa8ziUJbMar1J+oRQYb4I2ETS5aebI3xr1MQIecqH4/Yur/WjxsTCbqp2fIxGiBmtzLBH4h82nNe2zQiXbnHIf/eAFHOyGI2g9ji59+DXn4HH5ch3AN/cFcjb94+1UBfSR1oE1EOIUBaumv2OxaPM+WAFgOkoAQOQqKzx8VaxQyhFUNCfsHW4WgRO0QBDUd6EYj1lXUTQlZ7FuN3r+4Pp4LFMTcWHhAuvnQ2tseoI18VC7eNwo0ERIWlgATp+HjNq5WWGnAmQ0tX0WeNH2jSJFhkUixDa3uK6paHv0RARyCrzsWERoDqfJN3olovTW4aBqiCO6IjFP8cHxrSvIpiANt8tKq0F6GJAToXdljRdo5QqDrlWJLwyzgcx4LpTQIoPzRVdJuDMZBDQp003mRblY9Rufb8dWKrrHg5Ro6QtNhiitKWezFnWm45yk9fI9m1//B7A5hlZcPWSn+xIDmbaECQz8xPONDnL9jZ9TvJAOwIvq0GspPEeH8ZnXFSWNm1hcEKxO5ioUXuY=
  secret_access_key:
    secure: yBChDVEp2VGV6uqzmqotdOCyVKHgCz4SSbQOFTBjqW3nIuSR2cIQsPQYrVypiuT3EsfSnv666CfqZbfYbx0NtB8bFxtZ8VSHPRzz5VBhuiU7PTuVzuAKl4uc1BYITQ+yU4yfNHG8DSFRBn9FvPezx/W432kT8YIYmlUWniC2DUYul3J0KMqxo/qPfyKN/ZREuErj/VslZsQlWVNlzvMLl0FFl32q6w5TL3XKKJ8rabRloMYaZgD29HFjGz23k1GlCdw9aQYVvwfCcZ0DfBpo2EiPuYFvnCiD03VgL7fU9juTXMBqybcNnJuhXjm2nxeWJNtHiP7WD8f5GEumwMp5kmUxQkTZfca53LH6kVAwdl6G6ztoHWD8s6xPnQjFhXmegrQ+6qksp/sqmUFS/T9ASDiS/gG4HjMuhZxHdZcbPFXtiC2429gL3bTwznSFTOXEB3V5iyXtq9Tqne8tD5x0NvP/snnHLTawFLJ2BNZYJMyFgaFsZL3JWjWyB9l9xSEEx6Yb05is6j6XHgA2O0hVttixmsqWKRf2ztf38YDBcsMm+/Qk23oJr4WxCTVIRZ5nmm9xoiowQm8kTJCuRZ15DzEGGzYkUMKosy3qlhQauzPUO6/flsKFXGz0WjQoNLuNOrAVfoPIEdG7txHjLK3VSs0nkAsMGwjTDfyiYmBEsFU=
  on:
    branch: master
