language: node_js
node_js:
  - '4.3'
before_deploy:
  - npm prune --production
deploy:
  provider: lambda
  function_name: aws-events-should-make-sense
  module_name: aws-events-should-make-sense
  handler_name: makeSense
  role: arn:aws:iam::608300940987:role/lambda-aws-events-should-make-sense
  runtime: nodejs4.3
  timeout: 5
  memory_size: 128
  region: eu-west-1
  access_key_id:
    secure: 1U/ke3RT4Xrc82LfoAlCxyz1khmSjBnTtU9IZ0iob7d35y5+RD1XaVlMfqlHtuLpnCYi6luIKjPnEbdIzaZMmjlRbru2oW3/meULnd7eaMn9TFZBdbr5mGf60H9edpWkLq1O5vYu1QTDQtJqTHphAFfAt29Jvwc+CaP4v+XbnSRRQvUGcudzN/Xn3KsVqARBB6Zjbeic8ZY+eNubmuRdkK+YSD46G0paOlWdXSvJzQzKXNjn4jHB51pGinF6ydNp7XobibB1ZxxXpdztxl0rzqINOiuo6P80dwcqDAkrd+sUnpfPoP6HGMHmXWH++/pZ/ry3pAoisacDSs/wSF7waQLxCsK2UYwDHSOmyq1k7OgTnCcGuWpkurxz8swEy/Qy4MoAjbajBesoUIvSx6nRQTsQsfW+5nCUqDOfRBnkyiYM9ybga2b97KZvnA9PX6FaUnJ48VhoEBNoeAJ8ECgOvsHphbLP4JKss6Vd3fXWXt1ajZCXoC8NT/ffpR5ZiIW2SFtcSR8NsfO1jbwfvoiT3dTuVeSF8JdrwXC9NeTrbgy+e6IE9z27sqoBGv/Pta3U48cjhjTH7sF2hZZoDg3W1V4RE3+qxLAyDfPbWZiS6qehIidMW/v3aSRXepueXTpWjtLAxlL6HLyuqxqCKvVYNIJrfBMjanYUL034166fBEI=
  secret_access_key:
    secure: Jl4AtbdLd7VCe4HMDb68BmJMikHsJpfe1V2rPC+P9jt4QnXyxIqcNwjDtZmHfY4QugyE5OLccuxizB/QdD7SdtHfH11DzHRlk9TKZ2j0mXEC95dqVgjIMKH6aUdeQT340kQCgK4wnWbmFp6XivFtVMzxpQJ0K2WeYSSsdTYSnc9dCCHkAUn1F4jPzd5/KipZQITalSBYp5QfHHHaG0G+zVVm6C3IiqzzoMhlE1lS6HZ63Tsgnf1jTII3kqvpUlgPH4M2MtGMI8XRowAKF8fjUFlHEDLJqfYctx7W5P8lZ3aM3Lfsy808EN6pQxrLJnpPIiM6ZBbwxokEBvI6Azd4n70dLS/YDBejFqRdEYwKd8y4jtigN+uXx9P/2eUvY6K2rBW30gYWABBga563qttQ6bwtEw9W4Lsi/PTb9b6eLS3EeXKWis/KZcxk80bdhvBKSr6dRqqTVOnFkHNxideuVvHysdBDYwvn9obSYxh4vMr8PIQLLOXS8pDQFhgSmTQs/eeFO3gIZ4Ikns3tKDuj0RYi2kMV6Q8YeoPar9oyrI8C+9IR/9Zz/AcMN4P6QNfMRniSaBWQ6lR5olorkjCwNxO63LM/xeHSbp87ImRHNB8pdXd5k6B+eim+jDa7CzY07/qbXm3DVychEeSE5OJxV/xBaEiiFqOInpm9G2q5bws=
  on:
    branch: master
